### ISSUE TITLE
能写个example吗？

### ISSUE THREAD

**Issue by Leadrive** [neeboo/dva_flutter#1]
代码看起来不难，还是没掌握如何用，
能提供一个example吗？

**Comment by neeboo** [comment]
大概下周三，在清理repo

**Comment by neeboo** [comment]
可以看看这里，有问题和想法请随时提出来
[https://github.com/neeboo/dva_flutter_example](https://github.com/neeboo/dva_flutter_example)

**Comment by neeboo** [comment]
example written
