### ISSUE TITLE
CallEffect example

### ISSUE THREAD

**Issue by jimmyye** [neeboo/dva_flutter#2]
能说明下CallEffect应该怎么写吗？谢谢。

**Comment by neeboo** [comment]
现在CallEffect没有很好的实现，原因是在dart里头 yield不能返回结果 因此这里不能像dvajs那样用yield CallEffect，然而在dart里面async*是可以用await的 所以这里可以用await来替代。看看后面能不能把dart_saga移植过来，说不定能有好的办法。

**Comment by jimmyye** [comment]
是的，我刚才试过，只能用await。
其他redux方案太复杂了，幸好有dva_flutter，谢谢。
