### ISSUE TITLE
生命周期和context

### ISSUE THREAD

**Issue by JackyLeeCS** [neeboo/dva_flutter#3]
如果想到reducer或effect中用到context应该怎么实现，还有这个跟页面的生命周期怎么联系起来，例子中好像没有涉及到。

**Comment by neeboo** [comment]
dva_dart在初始化之后就会将store放置于context中，使用connector并传入context与store进行交互。

如果你需要在effect里面使用context，请在model中定义对应effects的方法，并传入context，比如这样
```dart
effects: {
  'sendContext': (Payload<Context> payload) async* {
   /// do with Payload and Context
  },
...
}
```

然而我不建议这样做，在effect里面尽量使用干净的数据进行处理，因为state最终也会用context下发。

请看这个container使用connector的例子

https://github.com/neeboo/dva_flutter_example/blob/master/lib/components/playPage/container.dart

页面生命周期我的理解其实是widget的生命周期，在connector中，builder里面传入你想连接的Widget和store对应的state，那么Widget里面的生命周期由它自行处理

不知道我有没有解释清楚，详细的例子请看

https://github.com/neeboo/dva_flutter_example

**Comment by JackyLeeCS** [comment]
如果我有一个需求是在登录完成之后要退出当前界面，不在effect里面使用context的话这个退出操作要放在哪里比较合适呢

**Comment by neeboo** [comment]
> 如果我有一个需求是在登录完成之后要退出当前界面，不在effect里面使用context的话这个退出操作要放在哪里比较合适呢

请在Connector里面处理传入的state，我们假设
```dart

....
builder: (BuildContext context, DvaModels models, dispatch) {
    
      LoginState loginState = models.getState('login');
      
      if(loginState==true){
        return OtherPage(
           /// render loginState===true
       );
      }else{
        return LoginPage(
         /// render loginState===false 
      )
      }
      
    },

```

当然你也可以进入LoginPage之后给他一个跳转，这里全部取决于你的页面想怎么做

如果你是在当前页面进行监听（比如仅改变按钮状态），当state传入的时候，就可以改变按钮状态，或者给你一个跳转或退出（可以考虑使用静态方法来操作）

**Comment by JackyLeeCS** [comment]
> > 如果我有一个需求是在登录完成之后要退出当前界面，不在effect里面使用context的话这个退出操作要放在哪里比较合适呢
> 
> 请在Connector里面处理传入的state，我们假设
> 
> ```dart
> ....
> builder: (BuildContext context, DvaModels models, dispatch) {
>     
>       LoginState loginState = models.getState('login');
>       
>       if(loginState==true){
>         return OtherPage(
>            /// render loginState===true
>        );
>       }else{
>         return LoginPage(
>          /// render loginState===false 
>       )
>       }
>       
>     },
> ```
> 
> 当然你也可以进入LoginPage之后给他一个跳转，这里全部取决于你的页面想怎么做
> 
> 如果你是在当前页面进行监听（比如仅改变按钮状态），当state传入的时候，就可以改变按钮状态，或者给你一个跳转或退出（可以考虑使用静态方法来操作）

大概明白了，谢谢

**Comment by JackyLeeCS** [comment]
> dva_dart在初始化之后就会将store放置于context中，使用connector并传入context与store进行交互。
> 
> 如果你需要在effect里面使用context，请在model中定义对应effects的方法，并传入context，比如这样
> 
> ```dart
> effects: {
>   'sendContext': (Payload<Context> payload) async* {
>    /// do with Payload and Context
>   },
> ...
> }
> ```
> 
> 然而我不建议这样做，在effect里面尽量使用干净的数据进行处理，因为state最终也会用context下发。
> 
> 请看这个container使用connector的例子
> 
> https://github.com/neeboo/dva_flutter_example/blob/master/lib/components/playPage/container.dart
> 
> 页面生命周期我的理解其实是widget的生命周期，在connector中，builder里面传入你想连接的Widget和store对应的state，那么Widget里面的生命周期由它自行处理
> 
> 不知道我有没有解释清楚，详细的例子请看
> 
> https://github.com/neeboo/dva_flutter_example

尝试了一下，生命周期这块还是没太明白，flutter里面只有statefulwidget有生命周期的概念，但是用了dva以后好像只能用statelesswidget了吧。可能是我理解有误，能帮忙给个简单的例子吗，例如我要在退出界面时清除dvastate里面的状态应该怎么做

**Comment by neeboo** [comment]
> > dva_dart在初始化之后就会将store放置于context中，使用connector并传入context与store进行交互。
> > 如果你需要在effect里面使用context，请在model中定义对应effects的方法，并传入context，比如这样
> > ```dart
> > effects: {
> >   'sendContext': (Payload<Context> payload) async* {
> >    /// do with Payload and Context
> >   },
> > ...
> > }
> > ```
> > 
> > 
> > 然而我不建议这样做，在effect里面尽量使用干净的数据进行处理，因为state最终也会用context下发。
> > 请看这个container使用connector的例子
> > https://github.com/neeboo/dva_flutter_example/blob/master/lib/components/playPage/container.dart
> > 页面生命周期我的理解其实是widget的生命周期，在connector中，builder里面传入你想连接的Widget和store对应的state，那么Widget里面的生命周期由它自行处理
> > 不知道我有没有解释清楚，详细的例子请看
> > https://github.com/neeboo/dva_flutter_example
> 
> 尝试了一下，生命周期这块还是没太明白，flutter里面只有statefulwidget有生命周期的概念，但是用了dva以后好像只能用statelesswidget了吧。可能是我理解有误，能帮忙给个简单的例子吗，例如我要在退出界面时清除dvastate里面的状态应该怎么做

例子可能暂时没有时间去写，用dva，stateless和stateful都是可以用的，所以你的statefulWidget怎么写都没有关系.

context(store) => connector(model) =>builder(statefulWidget/statelessWidget)

有关改变dvastate的状态，可以用两种途径

1） 在connector和widget中dispatch一个payload，调用model的effects
2） 在model里面使用effect，跨model调用reducer

我想过两天有空的时候再写个复杂的例子，不好意思，最近实在有些忙

**Comment by JackyLeeCS** [comment]
> > > dva_dart在初始化之后就会将store放置于context中，使用connector并传入context与store进行交互。
> > > 如果你需要在effect里面使用context，请在model中定义对应effects的方法，并传入context，比如这样
> > > ```dart
> > > effects: {
> > >   'sendContext': (Payload<Context> payload) async* {
> > >    /// do with Payload and Context
> > >   },
> > > ...
> > > }
> > > ```
> > > 
> > > 
> > > 然而我不建议这样做，在effect里面尽量使用干净的数据进行处理，因为state最终也会用context下发。
> > > 请看这个container使用connector的例子
> > > https://github.com/neeboo/dva_flutter_example/blob/master/lib/components/playPage/container.dart
> > > 页面生命周期我的理解其实是widget的生命周期，在connector中，builder里面传入你想连接的Widget和store对应的state，那么Widget里面的生命周期由它自行处理
> > > 不知道我有没有解释清楚，详细的例子请看
> > > https://github.com/neeboo/dva_flutter_example
> > 
> > 
> > 尝试了一下，生命周期这块还是没太明白，flutter里面只有statefulwidget有生命周期的概念，但是用了dva以后好像只能用statelesswidget了吧。可能是我理解有误，能帮忙给个简单的例子吗，例如我要在退出界面时清除dvastate里面的状态应该怎么做
> 
> 例子可能暂时没有时间去写，用dva，stateless和stateful都是可以用的，所以你的statefulWidget怎么写都没有关系.
> 
> context(store) => connector(model) =>builder(statefulWidget/statelessWidget)
> 
> 有关改变dvastate的状态，可以用两种途径
> 
> 1） 在connector和widget中dispatch一个payload，调用model的effects
> 2） 在model里面使用effect，跨model调用reducer
> 
> 我想过两天有空的时候再写个复杂的例子，不好意思，最近实在有些忙

好的
